  - name: payments in RoboShop e-commerce app
    hosts: payments
    become: yes
    tasks:
    - name: Install Python 3.6
      ansible.builtin.yum:
       name: "{{item}}"
       state: installed
      loop:
        - python36
        - gcc
        - python3-devel 
    
    - name: check if roboshop user exists or not
      ansible.builtin.command: id roboshop
      register: result
    
    - when: result.rc !=0
      name: Create roboshop user
      become: yes
      ansible.builtin.user:
      name: roboshop
